import type { Metadata } from 'next';
import { notoSans } from './components/ui/fonts';
import './globals.css';
import MMProvider from './components/ui/MMProvider';
import NavBar from './components/ui/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        <MMProvider>
          <NavBar />
          {children}
        </MMProvider>
      </body>
    </html>
  );
}
